# Generated by Django 4.1.3 on 2022-12-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bigcategory_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='shop.productlistings')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(related_name='product', to='shop.orderproduct')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='bigcategory_name_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bigcategory_name_id', to='shop.bigcategories'),
            preserve_default=False,
        ),
    ]
