# Generated by Django 4.1.3 on 2022-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bigcategories_orderproduct_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistings',
            name='image',
            field=models.ImageField(upload_to='product-img/'),
        ),
    ]
