# Generated by Django 4.1.3 on 2023-01-16 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comments_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='shop.comments')),
                ('disliked_user_id', models.ManyToManyField(blank=True, related_name='disliked_user_id', to=settings.AUTH_USER_MODEL)),
                ('liked_user_id', models.ManyToManyField(blank=True, related_name='liked_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
